require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.0
  TargetRailsVersion: 7.0
  NewCops: enable
  inherit_mode: merge

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120