# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DB_USERNAME', Rails.application.credentials.db.username) %>
  password: <%= ENV.fetch('DB_PASSWORD', Rails.application.credentials.db.password) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: digi_test_development

test:
  <<: *default
  database: digi_test_test

production:
  <<: *default
  database: digi_test_production
